language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

sudo: required

addons:
    apt:
        packages:
            - parallel

install:
    - git clone git://github.com/stricaud/faup.git
    - pushd faup/build
    - cmake .. && make
    - sudo make install
    - sudo ldconfig
    - popd
    - pushd faup/src/lib/bindings/python
    - python setup.py install
    - popd
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codecov
    - cp config.ini.sample config.ini

before_script:
    - redis-server /etc/redis/redis.conf --port 6334 --daemonize yes

script:
    - seq 10 | parallel -u -j 10 ./worker.py &
    - ./runapp.py
