language: python

python:
    - "2.7"

sudo: required

addons:
    apt:
        packages:
            - parallel

install:
    - git clone git://github.com/stricaud/faup.git
    - pushd faup/build
    - cmake .. && make
    - sudo make install
    - sudo ldconfig
    - popd
    - pushd faup/src/lib/bindings/python
    - python setup.py install
    - popd
    - pip install -r requirements.txt
    - pushd uwhoisd
    - python setup.py install
    - popd
    - pip install coveralls
    - pip install codecov
    - cp config.ini.sample config.ini

before_script:
    - redis-server /etc/redis/redis.conf --port 6334 --daemonize yes

script:
    - ./worker.py &
    - ./runapp.py &
    - sleep 30

after_success:
    - coveralls
    - codecov

