language: python

python:
    - "2.7"
    - "3.3"
    - "3.4"
    - "3.5"
    - "nightly"

sudo: required

services:
    - redis-server

addons:
    apt:
        packages:
            - parallel

install:
    - git clone git://github.com/stricaud/faup.git
    - cd faup
    - mkdir build
    - cd build
    - cmake .. && make
    - sudo make install
    - sudo ldconfig
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install codecov
    - cp config.ini.sample config.ini

script:
    - seq 10 | parallel -u -j 10 ./worker.py &
    - ./runapp.py
